### PR TITLE
Standardize license

### PR DESCRIPTION
**Pull request by ajorg-aws**
This helps license identification tools identify the license, and applies the license correctly, without changing the license or copyright.

### CODE REVIEW

**Comment by ajorg-aws** [comment]
Hello. We continue to run into the problem that license scanners don't identify the license in this project. Would you please consider accepting this PR?

**Comment by zzxwill** [comment]
> Hello. We continue to run into the problem that license scanners don't identify the license in this project. Would you please consider accepting this PR?

I also need this PR. How did you fix the issue afterward?

**Review by jamesls — APPROVED** [review]

**Comment by jamesls** [comment]
Thanks for updating!

**Comment by zzxwill** [comment]
@jamesls Please help create a new tag:)

**Comment by zzxwill** [comment]
@jamesls @jasdel @ejholmes @xibz Could anyone help create a new tag? Thanks.

**Pull request merged**
